#!/bin/bash

# Hướng dẫn build APK cho ứng dụng EV Swap

echo "📱 HƯỚNG DẪN BUILD APK CHO EV SWAP"
echo "=================================="
echo ""

echo "CÁCH 1: BUILD BẰNG EAS (KHUYẾN NGHỊ)"
echo "------------------------------------"
echo "1. Cài đặt EAS CLI:"
echo "   npm install -g eas-cli"
echo ""
echo "2. Đăng nhập Expo account:"
echo "   eas login"
echo ""
echo "3. Cấu hình project (lần đầu):"
echo "   cd /home/vanh/doan/ev-swap"
echo "   eas build:configure"
echo ""
echo "4. Build APK:"
echo "   eas build --platform android --profile preview"
echo ""
echo "   - Build sẽ chạy trên cloud (miễn phí)"
echo "   - Mất khoảng 10-15 phút"
echo "   - Link download APK sẽ hiện khi hoàn thành"
echo ""

echo "CÁCH 2: BUILD LOCAL (CẦN ANDROID STUDIO)"
echo "----------------------------------------"
echo "1. Cài đặt Android Studio và Android SDK"
echo "2. Set biến môi trường ANDROID_HOME"
echo "3. Chạy lệnh:"
echo "   cd /home/vanh/doan/ev-swap"
echo "   npx expo run:android --variant release"
echo ""

echo "LƯU Ý:"
echo "------"
echo "- Trước khi build, đảm bảo API_BASE_URL trong constants.ts"
echo "  đã đổi từ localhost sang IP thật của server"
echo "- File APK sẽ nằm trong thư mục android/app/build/outputs/apk/"
echo ""

echo "THAY ĐỔI API_BASE_URL:"
echo "---------------------"
echo "Mở file: /home/vanh/doan/ev-swap/constants.ts"
echo "Đổi: export const API_BASE_URL = \"http://192.168.80.120:3000\";"
echo "Thành: export const API_BASE_URL = \"http://<IP-SERVER-THẬT>:3000\";"
echo ""
